// Haunted Mound song database.
// Each entry: { title, artist, album }
// Sources: public streaming/discography listings (Last.fm tracklists).
const s = (title, artist, album) => ({ title, artist, album });

export const SONGS = [
  // ── Grave House (2019) · Sematary & Ghost Mountain ──────────────────────
  s("Fury Road", "Sematary & Ghost Mountain", "Grave House"),
  s("Nevada", "Sematary & Ghost Mountain", "Grave House"),
  s("Interstate", "Sematary & Ghost Mountain", "Grave House"),
  s("New Rocks", "Sematary & Ghost Mountain", "Grave House"),
  s("Goat Man", "Sematary & Ghost Mountain", "Grave House"),
  s("Orbs", "Sematary & Ghost Mountain", "Grave House"),
  s("Skin Mask", "Sematary & Ghost Mountain", "Grave House"),
  s("Dead by Dawn", "Sematary & Ghost Mountain", "Grave House"),
  s("Fury Road 2", "Sematary & Ghost Mountain", "Grave House"),
  s("Ready for the House", "Sematary & Ghost Mountain", "Grave House"),
  s("Stand Your Ground", "Sematary & Ghost Mountain", "Grave House"),
  s("Broken Angel Hospital", "Sematary & Ghost Mountain", "Grave House"),

  // ── Rainbow Bridge (2019) · Sematary ────────────────────────────────────
  s("Slaughter House", "Sematary", "Rainbow Bridge"),
  s("Reverence", "Sematary", "Rainbow Bridge"),
  s("Bunny Suit", "Sematary", "Rainbow Bridge"),
  s("Pain", "Sematary", "Rainbow Bridge"),
  s("Toolbox", "Sematary", "Rainbow Bridge"),
  s("Dental Floss", "Sematary", "Rainbow Bridge"),
  s("Creatine", "Sematary", "Rainbow Bridge"),
  s("Arson", "Sematary", "Rainbow Bridge"),
  s("IM RELOADING", "Sematary", "Rainbow Bridge"),
  s("Shotgun", "Sematary", "Rainbow Bridge"),
  s("Cemetery", "Sematary", "Rainbow Bridge"),
  s("The Great Mothman", "Sematary", "Rainbow Bridge"),

  // ── Rainbow Bridge 2 (2020) · Sematary ──────────────────────────────────
  s("Forever Intro", "Sematary", "Rainbow Bridge 2"),
  s("My Cutter", "Sematary", "Rainbow Bridge 2"),
  s("Funeral", "Sematary", "Rainbow Bridge 2"),
  s("Skellingtons", "Sematary", "Rainbow Bridge 2"),
  s("Red Mist", "Sematary", "Rainbow Bridge 2"),
  s("Hearsin'", "Sematary", "Rainbow Bridge 2"),
  s("Chandelier", "Sematary", "Rainbow Bridge 2"),
  s("Toothtaker", "Sematary", "Rainbow Bridge 2"),
  s("Duster Huffer", "Sematary", "Rainbow Bridge 2"),
  s("Skinwalker", "Sematary", "Rainbow Bridge 2"),
  s("Hogs", "Sematary", "Rainbow Bridge 2"),
  s("We Don't Dial 911", "Sematary", "Rainbow Bridge 2"),
  s("Scissor Hands", "Sematary", "Rainbow Bridge 2"),
  s("Desecration", "Sematary", "Rainbow Bridge 2"),

  // ── Rainbow Bridge 3 (2021) · Sematary ──────────────────────────────────
  s("God's Light Burns Upon My Flesh", "Sematary", "Rainbow Bridge 3"),
  s("Murder Ride", "Sematary", "Rainbow Bridge 3"),
  s("Chainsaw Party", "Sematary", "Rainbow Bridge 3"),
  s("I'm A Sinner", "Sematary", "Rainbow Bridge 3"),
  s("Skin Mask 2", "Sematary", "Rainbow Bridge 3"),
  s("Necromanser", "Sematary", "Rainbow Bridge 3"),
  s("Forest Fire", "Sematary", "Rainbow Bridge 3"),
  s("Creepin' Thru Da Woods", "Sematary", "Rainbow Bridge 3"),
  s("Come With Me to Hell", "Sematary", "Rainbow Bridge 3"),
  s("Goin' Mordum", "Sematary", "Rainbow Bridge 3"),
  s("Witching Hour", "Sematary", "Rainbow Bridge 3"),
  s("Skincarver", "Sematary", "Rainbow Bridge 3"),
  s("Meet by the River", "Sematary", "Rainbow Bridge 3"),
  s("Truey Jeans", "Sematary", "Rainbow Bridge 3"),
  s("Crucifixion", "Sematary", "Rainbow Bridge 3"),

  // ── Hundred Acre Wrist (2020) · Sematary & Ghost Mountain ───────────────
  s("HEFFALUMPS", "Sematary & Ghost Mountain", "Hundred Acre Wrist"),
  s("Louisville Slugger", "Sematary & Ghost Mountain", "Hundred Acre Wrist"),
  s("Tourniquet", "Sematary & Ghost Mountain", "Hundred Acre Wrist"),
  s("DEER GOD", "Sematary & Ghost Mountain", "Hundred Acre Wrist"),
  s("Taxidermy", "Sematary & Ghost Mountain", "Hundred Acre Wrist"),
  s("Sigil", "Sematary & Ghost Mountain", "Hundred Acre Wrist"),
  s("Johnny Cutter", "Sematary & Ghost Mountain", "Hundred Acre Wrist"),
  s("Goodbye Horses", "Sematary & Ghost Mountain", "Hundred Acre Wrist"),
  s("Nazgul", "Sematary & Ghost Mountain", "Hundred Acre Wrist"),
  s("Cleaver Valley", "Sematary & Ghost Mountain", "Hundred Acre Wrist"),

  // ── Screaming Forest (2021) · Sematary ──────────────────────────────────
  s("I Hail the Night", "Sematary", "Screaming Forest"),
  s("Rituals", "Sematary", "Screaming Forest"),
  s("Willows", "Sematary", "Screaming Forest"),
  s("Redwoods", "Sematary", "Screaming Forest"),
  s("Kamakrazee", "Sematary", "Screaming Forest"),
  s("Longhorns", "Sematary", "Screaming Forest"),
  s("Hockey Mask", "Sematary", "Screaming Forest"),
  s("Scarecraw", "Sematary", "Screaming Forest"),
  s("Spirits", "Sematary", "Screaming Forest"),
  s("Moon Shine", "Sematary", "Screaming Forest"),

  // ── Butcher House (2023) · Sematary ─────────────────────────────────────
  s("Haunted Mound Reapers", "Sematary", "Butcher House"),
  s("BABAYAGA", "Sematary", "Butcher House"),
  s("IN THA FIELD WHERE I FOUND U", "Sematary", "Butcher House"),
  s("Suffer", "Sematary", "Butcher House"),
  s("Hallowed Be My Wrist", "Sematary", "Butcher House"),
  s("HATE AND GASOLINE", "Sematary", "Butcher House"),
  s("Smokin out da Grave", "Sematary", "Butcher House"),
  s("Angelmakers", "Sematary", "Butcher House"),
  s("Burn a Cop Car", "Sematary", "Butcher House"),
  s("GO DIG MY GRAVE", "Sematary", "Butcher House"),
  s("Little Lamb", "Sematary", "Butcher House"),

  // ── Bloody Angel (2024) · Sematary ──────────────────────────────────────
  s("BLOODY ANGEL", "Sematary", "Bloody Angel"),
  s("Headlights", "Sematary", "Bloody Angel"),
  s("WENDIGO", "Sematary", "Bloody Angel"),
  s("Smoke Machine", "Sematary", "Bloody Angel"),
  s("Mordor", "Sematary", "Bloody Angel"),
  s("parking lot scarecrow", "Sematary", "Bloody Angel"),
  s("hockey mask 2", "Sematary", "Bloody Angel"),
  s("Sacrifyce", "Sematary", "Bloody Angel"),
  s("Buryd My Heart (Interlude)", "Sematary", "Bloody Angel"),
  s("Benadryl Angyl", "Sematary", "Bloody Angel"),
  s("Hearse Trucks", "Sematary", "Bloody Angel"),
  s("Barrow Wights", "Sematary", "Bloody Angel"),
  s("Black Wings My Team", "Sematary", "Bloody Angel"),
  s("Demon In Pain", "Sematary", "Bloody Angel"),
  s("DEAD TREES", "Sematary", "Bloody Angel"),
  s("Get Money N Die", "Sematary", "Bloody Angel"),

  // ── Burning Barn (2022) · Buckshot ──────────────────────────────────────
  s("Keepe Out", "Buckshot", "Burning Barn"),
  s("Revenant", "Buckshot", "Burning Barn"),
  s("Haunted Hayride", "Buckshot", "Burning Barn"),
  s("BARN OWLS", "Buckshot", "Burning Barn"),
  s("OVER THE HILLS", "Buckshot", "Burning Barn"),
  s("Hallow'd Ground", "Buckshot", "Burning Barn"),
  s("SAWMILL", "Buckshot", "Burning Barn"),
  s("If I Had a Gun", "Buckshot", "Burning Barn"),
  s("Long Walk Home", "Buckshot", "Burning Barn"),
  s("In The Morning", "Buckshot", "Burning Barn"),
  s("Break The Dawn", "Buckshot", "Burning Barn"),

  // ── Haunted Nation (2023) · Hackle ──────────────────────────────────────
  s("Make You Dance", "Hackle", "Haunted Nation"),
  s("Lash Out", "Hackle", "Haunted Nation"),
  s("Tose", "Hackle", "Haunted Nation"),
  s("Get Sum", "Hackle", "Haunted Nation"),
  s("de_dust2", "Hackle", "Haunted Nation"),
  s("No Reason", "Hackle", "Haunted Nation"),
  s("Winning Team", "Hackle", "Haunted Nation"),
  s("Casket City", "Hackle", "Haunted Nation"),
  s("Last Chapter", "Hackle", "Haunted Nation"),
  s("Fun All Night", "Hackle", "Haunted Nation"),
  s("Left My Heart In Houston", "Hackle", "Haunted Nation"),

  // ── Cutter Lane (2022) · Turnabout ──────────────────────────────────────
  s("Husqrider", "Turnabout", "Cutter Lane"),
  s("COFFIN TOWN", "Turnabout", "Cutter Lane"),
  s("Bolos", "Turnabout", "Cutter Lane"),
  s("Sickle", "Turnabout", "Cutter Lane"),
  s("Does", "Turnabout", "Cutter Lane"),
  s("Till Death Do of Me", "Turnabout", "Cutter Lane"),
  s("Graveyard Party", "Turnabout", "Cutter Lane"),
  s("Brethren", "Turnabout", "Cutter Lane"),
  s("Olde Highway 28", "Turnabout", "Cutter Lane"),
  s("Where The Fire Burns", "Turnabout", "Cutter Lane"),

  // ── October Country (2025) · Ghost Mountain ─────────────────────────────
  s("Moulder", "Ghost Mountain", "October Country"),
  s("Stalks", "Ghost Mountain", "October Country"),
  s("Kismet", "Ghost Mountain", "October Country"),
  s("Hovel", "Ghost Mountain", "October Country"),
  s("By the Flame", "Ghost Mountain", "October Country"),
  s("HIGHWAY HEX", "Ghost Mountain", "October Country"),
  s("The Lake", "Ghost Mountain", "October Country"),
  s("Kevlar", "Ghost Mountain", "October Country"),
  s("Familiar Stranger", "Ghost Mountain", "October Country"),
  s("DAMIEN", "Ghost Mountain", "October Country"),
  s("October Country", "Ghost Mountain", "October Country"),
  s("Wayside", "Ghost Mountain", "October Country"),
];

export default SONGS;
